"""Pydantic data contracts shared across the pipeline."""

from app.models.bundle import (
    SCHEMA_VERSION,
    CaptionMatch,
    EvidenceBundle,
    Flag,
    FlagStatus,
    FlagType,
    Keyframe,
    KeyframeView,
    Meta,
    Modality,
    SchemaVersionError,
    Scorecard,
    SceneDescription,
    Severity,
    TranscriptSegment,
    WebMatch,
    read_bundle,
    read_scorecard,
)

__all__ = [
    "SCHEMA_VERSION",
    "CaptionMatch",
    "EvidenceBundle",
    "Flag",
    "FlagStatus",
    "FlagType",
    "Keyframe",
    "KeyframeView",
    "Meta",
    "Modality",
    "SchemaVersionError",
    "Scorecard",
    "SceneDescription",
    "Severity",
    "TranscriptSegment",
    "WebMatch",
    "read_bundle",
    "read_scorecard",
]
